### ISSUE TITLE
"Invalid subscript type 'list'" - super short question

### ISSUE THREAD

**Issue by Myrtle7** [Hong-Revo/glmnetUtils#13]
Hello everyone! 

I am trying to make an output that includes x: a dataset of 6 variables and y: one numeric variable. 
I don't understand what the problem is, since y is num

> output = glmnet(x[train,], y[train], alpha = 1)
Error in y[train] : invalid subscript type 'list'

**Comment by Hong-Revo** [comment]
`y` may be numeric, but `train` looks to be a list. Also, this isn't related to glmnetUtils.
