### ISSUE TITLE
cvAlpha asking for newx

### ISSUE THREAD

**Issue by dschneiderch** [Hong-Revo/glmnetUtils#2]
I am trying to look at best alpha/lambda combo but predict with a fit from cvAlpha is asking for newx.

library(nycflights13)
library(dplyr)
library(glmnetUtils)

```
f2=flights %>% slice(1:150000)#makes fitting a little faster
cl=parallel::makePSOCKcluster(4)
cvalpha=cvAlpha.glmnet(arr_delay~distance+air_time+dep_time,data=f2,outerParallel=cl)
parallel::stopCluster(cl)

m1=cvalpha$modlist[[1]]
predict(m1,newdata=head(f2))

Error in predict.glmnet(object$glmnet.fit, newx, s = lambda, ...) : 
  You need to supply a value for 'newx'
```

where as this works fine:

```
cv0=cv.glmnet(arr_delay~distance+air_time+dep_time,data=f2,alpha=0)
predict(cv0,newdata=head(f2))

```

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin15.5.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] glmnetUtils_0.4    glmnet_2.0-5       foreach_1.4.3     
 [4] Matrix_1.2-6       dplyr_0.5.0        purrr_0.2.2       
 [7] readr_1.0.0        tidyr_0.6.0        tibble_1.2        
[10] ggplot2_2.1.0      tidyverse_1.0.0    nycflights13_0.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7      magrittr_1.5     munsell_0.4.3    colorspace_1.2-6
 [5] lattice_0.20-33  R6_2.1.2         plyr_1.8.4       tools_3.3.1     
 [9] parallel_3.3.1   grid_3.3.1       gtable_0.2.0     DBI_0.5         
[13] iterators_1.0.8  lazyeval_0.2.0   assertthat_0.1   codetools_0.2-14
[17] scales_0.4.0

**Comment by Hong-Revo** [comment]
The component models in the cvAlpha object are all "raw" cv.glmnet objects, ie with no formula information attached. You can predict from them using the predict(x, y) convention, ie predictor matrix and response vector,  not formula and data frame.

If you want to predict with a cvAlpha object I recommend using the `which` argument to select a model:

    m1 <- predict(cvalpha, newdata=head(f2), which=1)

**Comment by dschneiderch** [comment]
Thanks, I hadn't seen the specific predict.cvAlpha() and which argument.
Might be good to explain this and link to the predict doc from the cvAlpha
help page. I find this a general problem in R documentation where details
are sometimes buried multiple levels down in the documentation. Also, with
regards to choosing alpha, you mentioned on SO that the alpha/lambda 2d
grid can be quite noisy. you might consider some automated cv with mean
RMSE's such as proposed here:
http://ellisp.github.io/blog/2016/08/13/fitbit-lasso
Thanks again for a great package!

**Comment by Hong-Revo** [comment]
That's a good point re: the documentation. I'll move the help for the predict method into the main cvAlpha.glmnet page; that should work better.
