### ISSUE TITLE
cv.glmnet ignores nfolds arg

### ISSUE THREAD

**Issue by Hong-Revo** [Hong-Revo/glmnetUtils#20]
From Hirokazu Iwasawa:

> Hi,
> 
> Maybe a bug.
> Try:
>
>     set.seed(2018); plot(cv.glmnet(mpg ~ ., data=mtcars))
>     set.seed(2018); plot(cv.glmnet(mpg ~ ., data=mtcars, nfolds=5))
>     set.seed(2018); plot(cv.glmnet(mpg ~ ., data=mtcars, nfolds=1))
>The outputs are all the same.
The cv.glmnet.formula function seems not to deal with “nfolds” appropriately.

**Comment by Greenwind1** [comment]
Just curious.
In this case,  `what nfolds does cv.glmnet treat?`
default folds?

Thanks in advance.

**Comment by Hong-Revo** [comment]
How `glmnetUtils::cv.glmnet` works is that it passes all your arguments to `glmnet::cv.glmnet`, which does the actual work of model fitting/CV. In this case, the `nfolds` arg isn't being passed down, so `glmnet::cv.glmnet` will use its default value which is 10.

**Comment by Greenwind1** [comment]
@Hong-Revo 
I got it.
Thanks.

**Comment by Greenwind1** [comment]
@Hong-Revo 

I forgot to ask.
When will CRAN reflect this change?

Many thanks,

**Comment by Hong-Revo** [comment]
@Greenwind1 it should be submitted in the new year.

**Comment by Hong-Revo** [comment]
This should be showing up on CRAN in the next few days.
