### ISSUE TITLE
doubly parallel call to cva.glmnet

### ISSUE THREAD

**Issue by BenoitLondon** [Hong-Revo/glmnetUtils#21]
Thanks for this package!
It appears that I can't make work outer and inner parallel at same time in cva.glmnet, looks like only the outer parallel fires up. Could you provide an example on how to make it parallel on both ?
Cheers,
Benoit

**Comment by BenoitLondon** [comment]
I tried something like this ( I  have 40 cores on my machine)

`mga <- cva.glmnet(formula,
                 offset = log(duration),
                 family = "poisson",
                 data = my_data[1:400000],
                 sparse = TRUE,
                 parallel = TRUE,
                 outerParallel = {cl <- parallel::makeForkCluster(8);doMC::registerDoMC(5);cl},
                 checkInnerParallel = FALSE,
                 alpha = seq(0, 0.7, 0.1),
                 nfolds = 5,
                 nlambda = 30
                 )`

And also:
`doMC::registerDoMC(5);
mga <- cva.glmnet(formula,
                 offset = log(duration),
                 family = "poisson",
                 data = my_data[1:400000],
                 sparse = TRUE,
                 parallel = TRUE,
                 outerParallel =parallel::makeForkCluster(8),
                 checkInnerParallel = FALSE,
                 alpha = seq(0, 0.7, 0.1),
                 nfolds = 5,
                 nlambda = 30
                 )`

**Comment by Hong-Revo** [comment]
Setting `checkInnerParallel=FALSE` should let you do this. How are you checking that the inner and outer loops are parallelised?

**Comment by BenoitLondon** [comment]
Hi, yes I have set check to FALSE see the code above but it looks like it uses only 8 cores when I look in top on Linux.
I think I know why it doesn't kick in the inner parallel it s because I have to register the cluster on the child processes of the outer parallel but I have not access to this.
Maybe it s possible by adding a registerdoMC before each call to cv.glmnet? In CVA.glmnet.

**Comment by BenoitLondon** [comment]
No I don't get a warning but the inner loop is not parallelized as there is no cluster registered from the child process of the outer loop. Do you have a working example on a single Linux machine?

**Comment by Hong-Revo** [comment]
This doesn't seem to be related to glmnetUtils. If you're having trouble nesting different parallelisation schemes, try using a Psock cluster instead of forking.
