### ISSUE TITLE
does predict use sparse?

### ISSUE THREAD

**Issue by seanv507** [Hong-Revo/glmnetUtils#22]
maybe I misunderstand the code.
I am trying to use sparse on predict function, AFAIK it is not being used in predict method.  Also I need the design matrix to be consistent between train and test sets. I don't believe this is possible? I think I need to call make model components outside, store the xlevs and then call again for test data?

**Comment by Hong-Revo** [comment]
No, `predict` doesn't use sparse. That's used when fitting the model.

To make factor levels consistent, you can try `rbind`ing the test and train data, and then set the response for the test rows to NA.
