### ISSUE TITLE
Add alpha labels to plot

### ISSUE THREAD

**Issue by t-davidson** [Hong-Revo/glmnetUtils#23]
Thanks for creating this great package. I have a request for how it could be made a bit more user friendly. Currently when I call `plot()` after performing `cva.glmnet()` I see a nice plot with lots of lines showing the MSE by lambda for different alphas, but I cannot easily tell which line corresponds to which alpha. It would be helpful if there was a legend to indicate this.

**Comment by Hong-Revo** [comment]
Now in 1.1.3.

**Comment by t-davidson** [comment]
Awesome, thanks!
