### ISSUE TITLE
Adaptive Lasso

### ISSUE THREAD

**Issue by andland** [Hong-Revo/glmnetUtils#4]
Thanks for the package. It adds features that I have long wished glmnet had. One additional thing I've thought would be nice to add to glmnet is adaptive lasso. Just like the features you have implemented already, adaptive lasso is [pretty easy to implement](http://ricardoscr.github.io/how-to-adaptive-lasso.html), but annoying that you have to do so from scratch every time. Thanks!

**Comment by Hong-Revo** [comment]
That's not a bad idea. I'll see if I can add it in.

**Comment by Hong-Revo** [comment]
First cut at adaptiveNet:

```
adaptiveNet <- function(..., alpha=1, gamma=1, adaptive.wts=NULL)
{
    # estimate adaptive weights from ridge model if required
    if(is.null(adaptive.wts))
    {
        mod1 <- cv.glmnet(..., alpha=0)
        b1 <- coef(mod1, s="lambda.min")[-1]  # remove intercept
        adaptive.wts <- 1/pmax(abs(b1), .Machine$double.eps)^gamma
    }

    glmnet(..., alpha=alpha, penalty.factor=adaptive.wts)
}

cv.adaptiveNet <- function(..., alpha=1, gamma=1, adaptive.wts=NULL)
{
    # estimate adaptive weights from ridge model if required
    if(is.null(adaptive.wts))
    {
        mod1 <- cv.glmnet(..., alpha=0)
        b1 <- coef(mod1, s="lambda.min")[-1]  # remove intercept
        adaptive.wts <- 1/pmax(abs(b1), .Machine$double.eps)^gamma
    }

    cv.glmnet(..., alpha=alpha, penalty.factor=adaptive.wts)
}
```

**Comment by Hong-Revo** [comment]
Would be better to use glmnet `exclude` argument rather than setting penalty to infinity.

**Comment by Hong-Revo** [comment]
Interesting... the value of the penalty factor for excluded vars has an impact on the model.


    set.seed(12345)
    df <- data.frame(x=matrix(rnorm(1e5), ncol=100), y=rnorm(1000))

    pen <- c(rep(1, 50), rep(Inf, 50))
    excl <- which(is.infinite(pen))

    x <- as.matrix(df[1:100])
    y <- df$y

    glmnet(x, y, penalty.factor=pen, exclude=excl)
    #Error in elnet(x, is.sparse, ix, jx, y, weights, offset, type.gaussian,  : 
    #  NA/NaN/Inf in foreign function call (arg 9)

    pen[excl] <- 1
    glmnet(x, y, penalty.factor=pen, exclude=excl)
    # lambda ranges from 0.00017 to 0.0608

    pen[excl] <- 10000
    glmnet(x, y, penalty.factor=pen, exclude=excl)
    # lambda ranges from 0.866 to 304

**Comment by Hong-Revo** [comment]
Might be better to add interfaces to existing packages that can do this (and other variations on lasso/elastic net)

**Comment by Hong-Revo** [comment]
Not likely to happen at this stage
