### ISSUE TITLE
Missing data leads to error

### ISSUE THREAD

**Issue by Deleetdk** [Hong-Revo/glmnetUtils#6]
Missing data leads to an error.

Example:

```
> iris_na = iris
> iris_na[1, 1] = NA
> glmnet(Sepal.Length ~ ., data = iris_na)
Error in glmnet::glmnet(x = xy$x, y = xy$y, weights = xy$weights, offset = xy$offset,  : 
  number of elements in weights (150) not equal to the number of rows of x (149)
>  glmnet(Sepal.Width ~ ., data = iris_na)
Error in glmnet::glmnet(x = xy$x, y = xy$y, weights = xy$weights, offset = xy$offset,  : 
  number of elements in weights (150) not equal to the number of rows of x (149)
```

It doesn't matter whether it's the dependent or independent variable.

Easy solution is to just remove rows with missing data before running. I.e. subset data to the variables in the formula, and then call `na.omit`. Be sure to check if the result has nrow = 0 and throw an informative error.

**Comment by Hong-Revo** [comment]
fixed in a71388f0a742cb015b96e90b8d77ed4ca44d6126
